export enum units {
  zeptosecond = "zs",
  attosecond = "as",
  femtosecond = "fs",
  picosecond = "ps",
  nanosecond = "ns",
  microsecond = '\u00B5s',
  millisecond = "ms",
  second = "s",
  minute = "mi",
  hour = "h",
  day = "d",
  week = "w",
  month = "mo",
  quarter = "q",
  year = "y",
  decade = "dec",
  score = "sc",
  century = 'cen',
  millenia = 'mil'
}